package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.Manager;
import vn.com.vti.springexam.entity.ManagerExample;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    long countByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    int deleteByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    int insert(Manager row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    int insertSelective(Manager row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    List<Manager> selectByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    Manager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") Manager row, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    int updateByExample(@Param("row") Manager row, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(Manager row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    int updateByPrimaryKey(Manager row);
}