package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.Members;
import vn.com.vti.springexam.entity.MembersExample;

public interface MembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    long countByExample(MembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int deleteByExample(MembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int insert(Members row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int insertSelective(Members row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    List<Members> selectByExample(MembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    Members selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") Members row, @Param("example") MembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int updateByExample(@Param("row") Members row, @Param("example") MembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(Members row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int updateByPrimaryKey(Members row);
}