package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.OrderDetail;
import vn.com.vti.springexam.entity.OrderDetailExample;
import vn.com.vti.springexam.entity.OrderDetailKey;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    long countByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    int deleteByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    int deleteByPrimaryKey(OrderDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    int insert(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    int insertSelective(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    OrderDetail selectByPrimaryKey(OrderDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") OrderDetail row, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    int updateByExample(@Param("row") OrderDetail row, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    int updateByPrimaryKey(OrderDetail row);
}