package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.Supplier;
import vn.com.vti.springexam.entity.SupplierExample;

public interface SupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    long countByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int deleteByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int deleteByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int insert(Supplier row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int insertSelective(Supplier row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    List<Supplier> selectByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    Supplier selectByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") Supplier row, @Param("example") SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int updateByExample(@Param("row") Supplier row, @Param("example") SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(Supplier row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    int updateByPrimaryKey(Supplier row);
}