package vn.com.vti.springexam.entity;

import java.util.Date;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_desc
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private String categoryDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.created_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.updated_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.created_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.updated_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.image_url
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private String imageUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_desc
     *
     * @return the value of category.category_desc
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public String getCategoryDesc() {
        return categoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_desc
     *
     * @param categoryDesc the value for category.category_desc
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setCategoryDesc(String categoryDesc) {
        this.categoryDesc = categoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.created_by
     *
     * @return the value of category.created_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.created_by
     *
     * @param createdBy the value for category.created_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.updated_by
     *
     * @return the value of category.updated_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.updated_by
     *
     * @param updatedBy the value for category.updated_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.created_at
     *
     * @return the value of category.created_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.created_at
     *
     * @param createdAt the value for category.created_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.updated_at
     *
     * @return the value of category.updated_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.updated_at
     *
     * @param updatedAt the value for category.updated_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.image_url
     *
     * @return the value of category.image_url
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.image_url
     *
     * @param imageUrl the value for category.image_url
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
}