package vn.com.vti.springexam.entity;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_desc
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    private String categoryDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_desc
     *
     * @return the value of category.category_desc
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public String getCategoryDesc() {
        return categoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_desc
     *
     * @param categoryDesc the value for category.category_desc
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public void setCategoryDesc(String categoryDesc) {
        this.categoryDesc = categoryDesc;
    }
}