package vn.com.vti.springexam.entity;

import java.util.Date;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.username
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.last_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.first_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.birthday
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.address
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.id
     *
     * @return the value of manager.id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.id
     *
     * @param id the value for manager.id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.username
     *
     * @return the value of manager.username
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.username
     *
     * @param username the value for manager.username
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.last_name
     *
     * @return the value of manager.last_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.last_name
     *
     * @param lastName the value for manager.last_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.first_name
     *
     * @return the value of manager.first_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.first_name
     *
     * @param firstName the value for manager.first_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.birthday
     *
     * @return the value of manager.birthday
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.birthday
     *
     * @param birthday the value for manager.birthday
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.address
     *
     * @return the value of manager.address
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.address
     *
     * @param address the value for manager.address
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.created_by
     *
     * @return the value of manager.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.created_by
     *
     * @param createdBy the value for manager.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.updated_by
     *
     * @return the value of manager.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.updated_by
     *
     * @param updatedBy the value for manager.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.created_at
     *
     * @return the value of manager.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.created_at
     *
     * @param createdAt the value for manager.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.updated_at
     *
     * @return the value of manager.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.updated_at
     *
     * @param updatedAt the value for manager.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}