package vn.com.vti.springexam.entity;

import java.util.Date;

public class Members {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.id
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.username
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.last_name
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.first_name
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.birthday
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.address
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.created_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.updated_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.created_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.updated_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.password
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.id
     *
     * @return the value of members.id
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.id
     *
     * @param id the value for members.id
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.username
     *
     * @return the value of members.username
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.username
     *
     * @param username the value for members.username
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.last_name
     *
     * @return the value of members.last_name
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.last_name
     *
     * @param lastName the value for members.last_name
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.first_name
     *
     * @return the value of members.first_name
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.first_name
     *
     * @param firstName the value for members.first_name
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.birthday
     *
     * @return the value of members.birthday
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.birthday
     *
     * @param birthday the value for members.birthday
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.address
     *
     * @return the value of members.address
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.address
     *
     * @param address the value for members.address
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.created_by
     *
     * @return the value of members.created_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.created_by
     *
     * @param createdBy the value for members.created_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.updated_by
     *
     * @return the value of members.updated_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.updated_by
     *
     * @param updatedBy the value for members.updated_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.created_at
     *
     * @return the value of members.created_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.created_at
     *
     * @param createdAt the value for members.created_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.updated_at
     *
     * @return the value of members.updated_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.updated_at
     *
     * @param updatedAt the value for members.updated_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.password
     *
     * @return the value of members.password
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.password
     *
     * @param password the value for members.password
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setPassword(String password) {
        this.password = password;
    }
}