package vn.com.vti.springexam.entity;

import java.util.Date;

public class Members {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.id
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.username
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.last_name
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.first_name
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.birthday
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.address
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.id
     *
     * @return the value of members.id
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.id
     *
     * @param id the value for members.id
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.username
     *
     * @return the value of members.username
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.username
     *
     * @param username the value for members.username
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.last_name
     *
     * @return the value of members.last_name
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.last_name
     *
     * @param lastName the value for members.last_name
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.first_name
     *
     * @return the value of members.first_name
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.first_name
     *
     * @param firstName the value for members.first_name
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.birthday
     *
     * @return the value of members.birthday
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.birthday
     *
     * @param birthday the value for members.birthday
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.address
     *
     * @return the value of members.address
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.address
     *
     * @param address the value for members.address
     *
     * @mbg.generated Mon Mar 30 23:47:55 GMT+09:00 2026
     */
    public void setAddress(String address) {
        this.address = address;
    }
}