package vn.com.vti.springexam.entity;

public class OrderDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_detai_no
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    private Integer orderDetaiNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_no
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    private Integer orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_detai_no
     *
     * @return the value of order_detail.order_detai_no
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    public Integer getOrderDetaiNo() {
        return orderDetaiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_detai_no
     *
     * @param orderDetaiNo the value for order_detail.order_detai_no
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    public void setOrderDetaiNo(Integer orderDetaiNo) {
        this.orderDetaiNo = orderDetaiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_no
     *
     * @return the value of order_detail.order_no
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_no
     *
     * @param orderNo the value for order_detail.order_no
     *
     * @mbg.generated Thu Apr 23 21:43:27 GMT+09:00 2026
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }
}