package vn.com.vti.springexam.entity;

import java.util.Date;

public class OrderHeader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_header.order_no
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_header.member_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_header.order_datetime
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Date orderDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_header.payment_type
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private String paymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_header.member_card_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer memberCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_header.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_header.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_header.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_header.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_header.order_no
     *
     * @return the value of order_header.order_no
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_header.order_no
     *
     * @param orderNo the value for order_header.order_no
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_header.member_id
     *
     * @return the value of order_header.member_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_header.member_id
     *
     * @param memberId the value for order_header.member_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_header.order_datetime
     *
     * @return the value of order_header.order_datetime
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Date getOrderDatetime() {
        return orderDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_header.order_datetime
     *
     * @param orderDatetime the value for order_header.order_datetime
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setOrderDatetime(Date orderDatetime) {
        this.orderDatetime = orderDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_header.payment_type
     *
     * @return the value of order_header.payment_type
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_header.payment_type
     *
     * @param paymentType the value for order_header.payment_type
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_header.member_card_id
     *
     * @return the value of order_header.member_card_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getMemberCardId() {
        return memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_header.member_card_id
     *
     * @param memberCardId the value for order_header.member_card_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setMemberCardId(Integer memberCardId) {
        this.memberCardId = memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_header.created_by
     *
     * @return the value of order_header.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_header.created_by
     *
     * @param createdBy the value for order_header.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_header.updated_by
     *
     * @return the value of order_header.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_header.updated_by
     *
     * @param updatedBy the value for order_header.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_header.created_at
     *
     * @return the value of order_header.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_header.created_at
     *
     * @param createdAt the value for order_header.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_header.updated_at
     *
     * @return the value of order_header.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_header.updated_at
     *
     * @param updatedAt the value for order_header.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}