package vn.com.vti.springexam.entity;

import java.util.Date;

public class OrderDetail extends OrderDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_id
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.item_num
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Integer itemNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.created_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.updated_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.created_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.updated_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.product_id
     *
     * @return the value of order_detail.product_id
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.product_id
     *
     * @param productId the value for order_detail.product_id
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.item_num
     *
     * @return the value of order_detail.item_num
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Integer getItemNum() {
        return itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.item_num
     *
     * @param itemNum the value for order_detail.item_num
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setItemNum(Integer itemNum) {
        this.itemNum = itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.created_by
     *
     * @return the value of order_detail.created_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.created_by
     *
     * @param createdBy the value for order_detail.created_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.updated_by
     *
     * @return the value of order_detail.updated_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.updated_by
     *
     * @param updatedBy the value for order_detail.updated_by
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.created_at
     *
     * @return the value of order_detail.created_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.created_at
     *
     * @param createdAt the value for order_detail.created_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.updated_at
     *
     * @return the value of order_detail.updated_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.updated_at
     *
     * @param updatedAt the value for order_detail.updated_at
     *
     * @mbg.generated Sat Apr 25 18:48:28 GMT+09:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}