package vn.com.vti.springexam.entity;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.supplier_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer supplierId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.created_by
     *
     * @return the value of product.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.created_by
     *
     * @param createdBy the value for product.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updated_by
     *
     * @return the value of product.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updated_by
     *
     * @param updatedBy the value for product.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.created_at
     *
     * @return the value of product.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.created_at
     *
     * @param createdAt the value for product.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updated_at
     *
     * @return the value of product.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updated_at
     *
     * @param updatedAt the value for product.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.supplier_id
     *
     * @return the value of product.supplier_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.supplier_id
     *
     * @param supplierId the value for product.supplier_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }
}