package vn.com.vti.springexam.entity;

import java.util.Date;

public class Supplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.category_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.category_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.tel
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.address
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.email
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.category_id
     *
     * @return the value of supplier.category_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.category_id
     *
     * @param categoryId the value for supplier.category_id
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.category_name
     *
     * @return the value of supplier.category_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.category_name
     *
     * @param categoryName the value for supplier.category_name
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.tel
     *
     * @return the value of supplier.tel
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.tel
     *
     * @param tel the value for supplier.tel
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.address
     *
     * @return the value of supplier.address
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.address
     *
     * @param address the value for supplier.address
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.email
     *
     * @return the value of supplier.email
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.email
     *
     * @param email the value for supplier.email
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.created_by
     *
     * @return the value of supplier.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.created_by
     *
     * @param createdBy the value for supplier.created_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.updated_by
     *
     * @return the value of supplier.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.updated_by
     *
     * @param updatedBy the value for supplier.updated_by
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.created_at
     *
     * @return the value of supplier.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.created_at
     *
     * @param createdAt the value for supplier.created_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.updated_at
     *
     * @return the value of supplier.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.updated_at
     *
     * @param updatedAt the value for supplier.updated_at
     *
     * @mbg.generated Sat Apr 11 15:13:03 GMT+09:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}